trigger:
 - main

parameters:
  - name: environment
    displayName: Which Environment to deploy?
    type: string
    default: 'develop'
    values:
    - develop
    - preproduction
    - production
  
stages:
- stage: TaskSelected
  jobs:
  - job: colour
    steps:
      - ${{ if eq( parameters['environment'], 'develop') }}:
        - task: Bash@3
          displayName: task1
          inputs:
            targetType: inline
            script: |
              echo "task1 is used as environment: ${{parameters.environment}} was selected"
 
      - ${{ elseif eq( parameters['environment'], 'preproduction') }}:
        - task: Bash@3
          displayName: task2
          inputs:
            targetType: inline
            script: |
              echo "task2 is used as environment: ${{parameters.environment}} was selected"
 
      - ${{ else }}:
        - task: Bash@3
          displayName: task3
          inputs:
            targetType: inline
            script: |
              echo "task3 is used as environment: ${{parameters.environment}} was selected"

